### ISSUE TITLE
no response - id and key set

### ISSUE THREAD

**Issue by remserwis** [apexad/homebridge-eufy-robovac#4] opened 2019-08-29 04:51 UTC
after sniffing data and editing config.json I am getting  logs as follow:

when starting homebridge: 

> [8/29/2019, 7:35:41 AM] Loading 2 accessories...
> [8/29/2019, 7:35:41 AM] [Vacuum] Initializing Eufy RoboVac accessory...
> 111Config { accessory: 'Eufy RoboVac',
>   name: 'Vacuum',
>   ip: '192.168.5.92',
>   deviceId: '***********************',
>   localKey: '87076b12de34edb6' }
> Connecting...
> [8/29/2019, 7:35:41 AM] 
> 

and when opening Home app:

> Disconnected!
> Connecting...
> Connecting...
> Connecting...
> Connected!
> {}
> Disconnected!
> Connected!
> (node:17783) UnhandledPromiseRejectionWarning: Error: connection timed out
>     at Socket.client.setTimeout (/usr/lib/node_modules/homebridge-eufy-robovac/dist/index.js:1:23345)
>     at Object.onceWrapper (events.js:277:13)
>     at Socket.emit (events.js:189:13)
>     at Socket._onTimeout (net.js:446:8)
>     at listOnTimeout (timers.js:324:15)
>     at processTimers (timers.js:268:5)
> (node:17783) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:17783) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Every homebridge device is "no response" status after that.

Device ID masked intentionally.

**Comment by kaicherry** [comment] 2019-10-03 22:33
This issue was resolved, for me at least, via the pastebin below, replacing /usr/local/lib/node_modules/homebridge-eufy-robovac/dist/index.js:
https://pastebin.com/evYiCzqb

**Comment by remserwis** [comment] 2019-10-03 22:43
> This issue was resolved, for me at least, via the pastebin below, replacing /usr/local/lib/node_modules/homebridge-eufy-robovac/dist/index.js:
> https://pastebin.com/evYiCzqb

thank you for info...
I will try it today

**Comment by remserwis** [comment] 2019-10-03 23:18
Got it...Works... Thank You very much

BTW..if anybody has the problem like me I wanted to notice that it has to be one line with DeviceID or IP setting....not both.

**Comment by raulfunkie** [comment] 2019-10-16 13:55
here to confirm that @remserwis fix above paired with @kaicherry fix of index.js works.

The vacuum turns itself off on Homebridge (shows itself as off after a while, even if its still running). Progress, none the less.

**Comment by MonsterEnergy-wtf** [comment] 2020-03-04 20:52
@kaicherry can you please provide the source code for this change? It worked since last week or something before it started to have connection issues.
I would like to investigate further and therefore it would be nice if you can share the sources, please?

Thanks in advance

**Comment by joshstrange** [comment] 2020-05-14 23:34
@kaicherry I was also wondering if you could provide that source code so I can make updates and re-release it. I have other people asking about it as well.

**Comment by ElBob** [comment] 2020-05-15 04:15
Confirming as well that this fixed it for me.

**Comment by apexad** [comment] 2020-05-21 02:29
@joshstrange I assume changed made to python package in this commit https://github.com/mitchellrj/eufy_robovac/commit/c5f392c63143ae2feaec1bfea9b066b9068abe1e need to be made to the nodeJS version https://github.com/joshstrange/eufy-robovac
Pastebin above is actually from here: https://github.com/joshstrange/homebridge-eufy-robovac/issues/3 so it seems @crazywako is the one that actually already made these changes but did not submit a PR.

I'd really like to get my vacuum back into HomeKit so please look into this if you can.  I may look into it soon if no one else does.

**Comment by joshstrange** [comment] 2020-05-21 19:57
@apexad, yikes... a lot of those changes are down in the Tuya library, I updated the version I used in https://github.com/joshstrange/eufy-robovac a while back and bumped this version back in March. The changes made to the rest of the code (Tuya-aside) seem minor. I'll be honest I'm probably not going to dedicate much time to this because I don't use this plugin anymore.

I am happy to merge requests or even discuss transferring the repo/adding committers, it's just not something I have time for right now.

**Comment by apexad** [comment] 2020-05-21 20:07
@joshstrange please add me as a contributor in GitHub (npmjs too please; same username).

I’ve got a few other things I am working on, so not exactly sure when I will get to it, but definitely want this plugin working again.

**Comment by MonsterEnergy-wtf** [comment] 2020-05-21 20:25
Let's see if I can spend a bit of my time to re-engineer this code. I guess the changes related to the "hacked" index.js are not that large. I tried it some weeks ago but I stopped it due missing time.
Not sure if it helps but maybe we can resolve the issue together.

**Comment by apexad** [comment] 2020-05-21 20:29
Assuming I find the time and get this working again, we can discuss transfer.

**Comment by MonsterEnergy-wtf** [comment] 2020-05-23 19:31
https://github.com/joshstrange/homebridge-eufy-robovac/issues/8#issuecomment-632886842

**Comment by apexad** [comment] 2020-05-23 20:50
@joshstrange As mentioned in #8, using the versions in my PRs on both of your repos and setting deviceId, not IP address. It seems to work.  Need to work on removing IP Address as an option and also want to add a config.schma.json and get this plugin homebridge verified.  Do you mind transferring both repos to me? and adding me on npmjs?

**Comment by joshstrange** [comment] 2020-05-23 21:40
@apexad you should have full access to Github and Npm. Let me know if you need anything else. Thank you for your help!

**Comment by apexad** [comment] 2020-05-23 21:50
Duplicate of #3 #8 #1 
This should now be fixed as well. However, please note, it seems IP address is no longer supported by the Tuya API (used by this plugin). Please switch to deviceId if you are using IP address. I will update the plugin README and such to reflect this soon.

**Closed as completed by apexad** 2020-05-23 21:50 UTC
