### ISSUE TITLE
Robovac Error

### ISSUE THREAD

**Issue by breekpunt** [apexad/homebridge-eufy-robovac#22] opened 2020-07-24 14:35 UTC
Hi,

I just installed this plugin and when robovac is cleaning, I'm getting a Robovac Error.
After the error all my Homekit accessories are not available anymore.
I turned the debuglog on and this is what's going on:

Found device 78551441bcddc23bf1e4 at 192.168.1.5
Connecting...
Found device 78551441bcddc23bf1e4 at 192.168.1.5
Connecting...
Found device 78551441bcddc23bf1e4 at 192.168.1.5
Connecting...
Found device 78551441bcddc23bf1e4 at 192.168.1.5
Connecting...
Connected!
Connected!
Robovac Error {}
Disconnected!
Disconnected!
(node:24753) UnhandledPromiseRejectionWarning: Error: connection timed out
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:302:18)
    at Object.onceWrapper (events.js:416:28)
    at Socket.emit (events.js:310:20)
    at Socket._onTimeout (net.js:479:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:24753) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24753) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Connected!
Robovac Error {}
Disconnected!
Status Updated!
Robovac Error {}
Disconnected!

Can you help me out?
Thanks,

Rob

**Comment by apexad** [comment] 2020-07-25 08:35
Duplicate of #21 
Looking into this and will hopefully get it fixed this weekend.

**Closed as completed by apexad** 2020-07-25 08:35 UTC
