### ISSUE TITLE
Issues with the RoboVac Plugin

### ISSUE THREAD

**Issue by R3ngadechaZzz** [apexad/homebridge-eufy-robovac#37] opened 2021-12-23 22:08 UTC
All is setup properly and appropriately within my homebridge.

All works great in my apple HomeKit too. However, only for a short period. Maybe a few hours. I can call it through Siri to start, stop. Etc. As I said all works great.

The error I get thrown is (As well as others of the same nature): 
- _This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.

Ive put the plugin into a child bridge on the homebridge UI, I’ve restarted the server, the docker container, reset the entire homebridge, apple HomeKit, the lot.

I have the correct deviceID and LocalKey too.

I am aware you have said in previous posts on Reddit and on here that the plugin needs to be rebuilt from the ground up. However I’m unsure as to whether this has been done or not in the year since you last posted on Reddit about this plugin. 

I am really hoping you might be able to help as this plugin would really help my disabled parter work the hoover without needing to push buttons etc. As its been setup by myself to work with automations within apple HomeKit.

Thanks in advance.

**Comment by apexad** [comment] 2021-12-28 13:41
Duplicate of #34 
I have it had a chance to work in this yet.

**Closed as completed by apexad** 2021-12-28 13:41 UTC
