### ISSUE TITLE
Control Robovac via home app switches itself off.

### ISSUE THREAD

**Issue by ollyboon** [apexad/homebridge-eufy-robovac#2] opened 2019-07-22 20:14 UTC
**As title says, Robovac (15C) turns off after turning on in HomeKit. What happens is very similar to the quick test command @mitchellrj talks about in eufy-robovac.**

> Where command is either "quickTest" or "status". The quickTest command will:
> 
> Connect to your device
> Print out the current statuses
> Start cleaning
> Wait 10 seconds
> Pause cleaning
> Wait 1 second
> Send device home
> Wait 1 second
> Disconnect & exit

### For me:
Press "turn fan on" for Robovac in HomeKit. 
Vacuum turns on and exits base.
Switch in HomeKit turns itself off.
Vacuum beeps and returns to base.
Vacuum beeps again and begins charging. 

Turning on in HomeKit reproduces this every time. 

Attempted restart homebridge & reboot Pi. 

Systemctl log when I turn robotic on via home app:

`Jul 22 21:04:49 raspberrypi homebridge[28021]:     "2": true
Jul 22 21:04:49 raspberrypi homebridge[28021]: }
Jul 22 21:04:49 raspberrypi homebridge[28021]: Status Updated!
Jul 22 21:04:49 raspberrypi homebridge[28021]: Status Updated!
Jul 22 21:04:49 raspberrypi homebridge[28021]: Status Updated!
Jul 22 21:04:50 raspberrypi homebridge[28021]: Setting: {
Jul 22 21:04:50 raspberrypi homebridge[28021]:     "2": false
Jul 22 21:04:50 raspberrypi homebridge[28021]: }
Jul 22 21:04:50 raspberrypi homebridge[28021]: Status Updated!
Jul 22 21:04:51 raspberrypi homebridge[28021]: Status Updated!
Jul 22 21:04:51 raspberrypi homebridge[28021]: Status Updated!
Jul 22 21:04:52 raspberrypi homebridge[28021]: Setting: {
Jul 22 21:04:52 raspberrypi homebridge[28021]:     "101": true
Jul 22 21:04:52 raspberrypi homebridge[28021]: }
`

**Comment by ollyboon** [comment] 2019-07-22 20:24
### Update: If go into HomeKit group for the robovac and navigate to the the vac accessory specifically control seems to work. 

**This happens:**
Turn on robovac in home app by selecting accessory inside group.
Vac turns on and begins cleaning.
Button in home app turns off.
Vac continues cleaning.
Turn on again in home app.
Vac continues cleaning.
(Vac is now cleaning and is displayed as 'ON' on home app).
Turn vac off in home app.
Vac beeps and returns home and begins charging.

This seems to work fine but requires me turning the vac on twice in the home app to function properly.
(accessory state does not reflect power state of Eufy 15C).

Hope this Info helps @joshstrange ?

![IMG_52D5C16CCA9D-1](https://user-images.githubusercontent.com/5742786/61662782-01317a80-acc7-11e9-972e-f1ff1bc8eea5.jpeg)

**Comment by joshstrange** [comment] 2019-07-22 20:36
@ollyboon Interesting, I don't group mine and I honestly don't know how the Eufy will react to both those modes getting flipped on at the same time (my assumption of what happens when you trigger them as a group).

You second post does help and I did see the behavior you are mentioning when I was testing it but couldn't pin it down to what was going wrong. To be perfectly honest with you it's not very high on my list to track down what the root cause as I have a couple other irons in the fire that are taking most of my free time currently. I would be be more than happy to look at a PR if you would like to take a crack at it but I 100% understand if that's not something you want to do. 

It's probably some stupid homekit mistake I'm making (I roughed this plugin together from looking at other homekit plugins). I am truly sorry that I'm not able to help more at this moment.

**Comment by ollyboon** [comment] 2019-07-22 20:46
@joshstrange No worries. I'm not familiar with writing homebridge plugins so don't think I'd be of much help. From a bit more testing it seems iOS13 automatically creates these groups with no option to ungroup (Image below). iOS12 works perfectly fine. Hopefully this is something that sorts itself out with GM seed. Thanks for the reply 👍 

![IMG_8538767B4789-1](https://user-images.githubusercontent.com/5742786/61664125-122fbb00-acca-11e9-8121-2a36f0b78abd.jpeg)

**Comment by raulfunkie** [comment] 2019-10-16 13:58
@ollyboon did you ever get around fixing or finding a solution for the off-status in HomeKit? currently experiencing that and was curious as to wether you found a solution.

**Comment by apexad** [comment] 2020-05-23 23:55
So, indeed, it is highly recommended that you manually switch these to ‘Show as Single Tiles’ (or whatever it is) versus the default group so you do not accidentally active it and also do a ‘Find’.

**Comment by apexad** [comment] 2020-05-23 23:56
Assuming this is the issue, I am closing this. Please re-open if still having the issue.

**Closed as completed by apexad** 2020-05-23 23:56 UTC
