### ISSUE TITLE
Plugin stopped working 

### ISSUE THREAD

**Issue by damon021** [apexad/homebridge-eufy-robovac#32] opened 2021-02-17 17:06 UTC
Hello,

I've been using the plugin on Hoobs for a while now and everything was working flawlessly. Last night all of a sudden, it completely stopped working and the status is stuck on "Updating". I reinstalled the plugin but nothing's changed.

Any tips?

**Comment by MonsterEnergy-wtf** [comment] 2021-02-17 18:09
Yes. From my side I restart Homebridge every 15 minutes via cron. This resolves the issue. Definitely not ideal but working.

**Comment by Kris8768** [comment] 2021-02-18 18:59
> Yes. From my side I restart Homebridge every 15 minutes via cron. This resolves the issue. Definitely not ideal but working.

Do you have the cron job within a docker container of any chance?

**Comment by MonsterEnergy-wtf** [comment] 2021-02-18 19:04
Depends on the docking container and how long it takes to come up.

Within the docking container - most liekely no. But you could restart the docker container. Should work. At least you could gibe it a try. 

I'm interested if this is working for you.

**Comment by damon021** [comment] 2021-02-19 13:34
> 
> 
> Yes. From my side I restart Homebridge every 15 minutes via cron. This resolves the issue. Definitely not ideal but working.

**Comment by damon021** [comment] 2021-02-19 13:35
I migate

**Comment by damon021** [comment] 2021-02-19 13:36
> 
> 
> Yes. From my side I restart Homebridge every 15 minutes via cron. This resolves the issue. Definitely not ideal but working.

The problem is it doesn't work with a simple restart and I have to uninstall and reinstall the plugin.

**Comment by damon021** [comment] 2021-02-19 18:35
this is part of my homebridge log:

`Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:622:13
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Connecting...
Robovac Error {}
Robovac Error {}
Robovac Error {}`

**Comment by apexad** [comment] 2021-02-22 06:23
Duplicate of #30 more or less.  I'm planning on re-writing this plugin soon, so trying to clear issues that are similar.

**Closed as completed by apexad** 2021-02-22 06:23 UTC
