### ISSUE TITLE
Feature request: Spot cleaning

### ISSUE THREAD

**Issue by niggydotcom** [apexad/homebridge-eufy-robovac#29] opened 2021-01-03 18:34 UTC
Hi could I ask it to spot clean rather than using the Eufy app?

**Comment by apexad** [comment] 2021-01-03 20:32
Basically a duplicate of #24 and yes, I plan to add this, but first there is a lot of underlying work that I want to do with this plugin and library when I get some time.

**Closed by apexad** 2021-01-03 20:32 UTC
Labels: duplicate
